version: '3'
services:
  node:
    image: node:18.15.0-alpine
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mvertes/alpine-mongo
